# Generated by Django 6.0.5 on 2026-06-06 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ArbitrageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('margin', models.FloatField()),
                ('volume_base', models.FloatField()),
                ('volume_quote', models.FloatField()),
                ('arbitrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderbooks.arbitrage')),
            ],
        ),
        migrations.CreateModel(
            name='Orderbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderbooks.exchange')),
            ],
        ),
        migrations.AddField(
            model_name='arbitrage',
            name='ob_buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orderbooks.orderbook'),
        ),
        migrations.AddField(
            model_name='arbitrage',
            name='ob_sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orderbooks.orderbook'),
        ),
        migrations.CreateModel(
            name='OrderbookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('asks', models.JSONField()),
                ('bids', models.JSONField()),
                ('orderbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderbooks.orderbook')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderbooks.market')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orderbooks.token')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orderbooks.token')),
                ('settle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orderbooks.token')),
            ],
        ),
        migrations.AddField(
            model_name='orderbook',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderbooks.symbol'),
        ),
        migrations.AlterUniqueTogether(
            name='arbitrage',
            unique_together={('ob_buy', 'ob_sell')},
        ),
        migrations.AlterUniqueTogether(
            name='orderbook',
            unique_together={('symbol', 'exchange')},
        ),
    ]
