# Generated by Django 6.0.5 on 2026-06-03 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderbooks.market')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orderbooks.token')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orderbooks.token')),
                ('settle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orderbooks.token')),
            ],
        ),
        migrations.CreateModel(
            name='Arbitrage',
            fields=[
                ('pk', models.CompositePrimaryKey('buy_exchange', 'buy_symbol', 'sell_exchange', 'sell_symbol', 'timestamp', blank=True, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('margin', models.FloatField()),
                ('volume_base', models.FloatField()),
                ('volume_quote', models.FloatField()),
                ('buy_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orderbooks.exchange')),
                ('sell_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orderbooks.exchange')),
                ('buy_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orderbooks.symbol')),
                ('sell_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orderbooks.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Orderbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('asks', models.JSONField()),
                ('bids', models.JSONField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderbooks.exchange')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderbooks.symbol')),
            ],
            options={
                'unique_together': {('symbol', 'exchange', 'timestamp')},
            },
        ),
    ]
