# Generated by Django 6.0.5 on 2026-06-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbookdata',
            name='id',
        ),
        migrations.AddField(
            model_name='orderbookdata',
            name='pk',
            field=models.CompositePrimaryKey('orderbook_id', 'timestamp', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='arbitragedata',
            unique_together={('arbitrage', 'timestamp')},
        ),
    ]
