# Generated by Django 6.0.5 on 2026-06-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbooks', '0002_remove_orderbookdata_id_orderbookdata_pk_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arbitragedata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='arbitragedata',
            name='pk',
            field=models.CompositePrimaryKey('arbitrage_id', 'timestamp', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='arbitragedata',
            name='id',
        ),
    ]
