# Generated by Django 6.0.6 on 2026-07-06 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderbooks', '0003_alter_arbitragedata_unique_together_arbitragedata_pk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragedata',
            name='arbitrage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orderbooks.arbitrage'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_base', to='orderbooks.token'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_quote', to='orderbooks.token'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='settle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbol_settle', to='orderbooks.token'),
        ),
    ]
